spring:
  application:
    name: ms-eureka

server:
  port: ${PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: ${EUREKA_HOST:localhost}
  server:
    renewal-percent-threshold: 0.90